/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Example: typeof import('./components/LayerFilter/example.vue')['default']
    LayerFilter: typeof import('./components/LayerFilter/index.vue')['default']
    LhLayerFilter: typeof import('@/components/LayerFilter/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecretDisplay: typeof import('./components/SecretDisplay/index.vue')['default']
  }
}
